-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.9.0.99.2
-- Module  Version: 5.4
-- Tue Jan 23 07:13:28 2018

-- parameterized module component declaration
component ROM41C
    port (Address: in  std_logic_vector(13 downto 0); 
        OutClock: in  std_logic; OutClockEn: in  std_logic; 
        Reset: in  std_logic; Q: out  std_logic_vector(9 downto 0));
end component;

-- parameterized module component instance
__ : ROM41C
    port map (Address(13 downto 0)=>__, OutClock=>__, OutClockEn=>__, 
        Reset=>__, Q(9 downto 0)=>__);
